-- Q1
CREATE TABLE BILL (
    BILLNO       NUMBER(10) PRIMARY KEY,
    BILLDATE     DATE,
    BILLAMOUNT   NUMBER(10,2),
    DISCOUNT     NUMBER(5,2),
    NETPAYMENT   NUMBER(10,2)
);

CREATE OR REPLACE TRIGGER SUTO_BILL
BEFORE INSERT OR UPDATE ON BILL
FOR EACH ROW
BEGIN
    IF :NEW.BILLAMOUNT <= 1000 THEN
        :NEW.DISCOUNT := 5;
    ELSIF :NEW.BILLAMOUNT >= 1000 AND :NEW.BILLAMOUNT <= 10000 THEN
        :NEW.DISCOUNT := 10;
    ELSIF :NEW.BILLAMOUNT >10000 THEN
        :NEW.DISCOUNT := 20;
    END IF;

    :NEW.NETPAYMENT := :NEW.BILLAMOUNT - ((:NEW.BILLAMOUNT * :NEW.DISCOUNT)/100);
END;

-- Q2
CREATE TABLE VEHICLETAXCATEGORYMASTER (
    VEHICLECATEGORYID       INT PRIMARY KEY,
    VEHICLECATEGORYNAME     VARCHAR2(50),
    VEHICLECATEGORYTAXRATE  NUMBER(5,2)
);

CREATE TABLE REGISTRATIONMASTER (
    REGISTRATIONID      INT PRIMARY KEY,
    REGISTRATIONDATE    DATE,
    OWNERNAME           VARCHAR2(20),
    VEHICLECATEGORYID   INT,
    VEHICLEBASICCOST    NUMBER(10,2),
    VEHICLETAXAMOUNT    NUMBER(9,2),
    VEHICLETOTALCOST    NUMBER(11,2),
    FOREIGN KEY (VEHICLECATEGORYID) REFERENCES VEHICLETAXCATEGORYMASTER(VEHICLECATEGORYID)
);

CREATE OR REPLACE TRIGGER AUTOINSERT
BEFORE INSERT OR UPDATE ON REGISTRATIONMASTER
FOR EACH ROW 
DECLARE 
    TEMPTEX VEHICLETAXCATEGORYMASTER.VEHICLECATEGORYTAXRATE%TYPE;
BEGIN
    SELECT VEHICLECATEGORYTAXRATE INTO TEMPTEX
    FROM VEHICLETAXCATEGORYMASTER
    WHERE VEHICLECATEGORYID = :NEW.VEHICLECATEGORYID;

    :NEW.VEHICLETAXAMOUNT := (:NEW.VEHICLEBASICCOST * TEMPTEX) / 100;
    :NEW.VEHICLETOTALCOST := :NEW.VEHICLEBASICCOST + :NEW.VEHICLETAXAMOUNT;
END;

-- Q3